import type { LegacyStar, Size } from '../types/star';

export const imageSize: Size = {
  width: 1920,
  height: 1080
};

export const legacyCopyPoint = { x: 1600, y: 900 };

export const legacyStars: LegacyStar[] = [
  {
    id: 'star-1',
    x: 512,
    y: 158,
    size: 2.5,
    label: 'Confucius',
    description: 'The Man Who Believed Character Shapes Civilization',
    story: {
      title: 'Confucius',
      years: '551–479 BC',
      tagline: 'The Man Who Believed Character Shapes Civilization',
      paragraphs: [
        'Many people looked at society and saw disorder.',
        'Confucius looked at the same world and believed it could be improved.',
        'Not through force.',
        'Not through wealth.',
        'But through the character of ordinary people.',
        'When others asked how to govern a nation, he often spoke about something much smaller.',
        'A son honoring his parents.',
        'A friend keeping his word.',
        'A person choosing what is right over what is easy.',
        'He believed that great societies are built from small acts of virtue.',
        'His greatest gift to humanity was not a political system.',
        'It was the conviction that moral growth matters.',
        'That individuals can cultivate themselves.',
        'That families, communities, and nations become stronger when people strive to live with integrity.',
        'For more than two thousand years, generations of teachers, scholars, leaders, and families have been shaped by this belief.',
        'Entire civilizations were influenced by his ideas.',
        'Yet Confucius was not a man who claimed to have all the answers.',
        'He spent his life learning, questioning, teaching, and refining his understanding of what it means to live well.',
        'He often spoke of humility.',
        'Of lifelong learning.',
        'Of the endless pursuit of becoming a better person.',
        'His life reminds us that wisdom is not something we possess.',
        'It is something we practice.',
        'His legacy is not a collection of ancient sayings.',
        'His legacy is a way of living.',
        'To respect others.',
        'To act with integrity.',
        'To keep learning.',
        'And to recognize that personal character shapes the world around us.',
        'Long after his words were first spoken, this spirit endures.',
        "Every time someone chooses virtue over convenience, seeks wisdom over pride, or strives to become a better human being, a small part of Confucius's legacy lives on."
      ]
    },
    delay: '0s',
    duration: '3.2s'
  },
  {
    id: 'star-2',
    x: 722,
    y: 168,
    size: 3,
    label: 'Isaac Newton',
    description: 'The Man Who Believed the Universe Could Be Understood',
    story: {
      title: 'Isaac Newton',
      years: '1643–1727',
      tagline: 'The Man Who Believed the Universe Could Be Understood',
      paragraphs: [
        'Many people looked at the world and saw mystery.',
        'Newton looked at the same world and believed it could be explained.',
        'When an apple fell from a tree, he did not simply see an apple falling.',
        'He saw a question.',
        'And behind that question, he believed there must be an answer.',
        'His greatest gift to humanity was not gravity.',
        'It was the conviction that nature follows laws.',
        'That the universe is not chaos.',
        'That reason can uncover truths hidden beneath appearances.',
        'Generations of scientists, engineers, inventors, and explorers would build upon this belief.',
        'The modern world stands on that foundation.',
        'Yet Newton was not merely a man of certainty.',
        'He spent much of his life wrestling with questions no equation could solve.',
        'He studied theology, alchemy, and the mysteries of existence with the same intensity he brought to mathematics.',
        'His life reminds us that even the greatest minds are driven by wonder.',
        'His legacy is not a set of formulas.',
        'His legacy is a way of seeing the world.',
        'To observe carefully.',
        'To question deeply.',
        'To think independently.',
        'And to believe that understanding is possible.',
        'Long after his discoveries are taught in classrooms, this spirit endures.',
        "Every time someone asks “Why?” and refuses to stop searching for an answer, a small part of Newton's legacy lives on."
      ]
    },
    delay: '0.5s',
    duration: '3.6s'
  },
  {
    id: 'star-3',
    x: 858,
    y: 150,
    size: 2,
    label: 'Mother Teresa',
    description: 'The Woman Who Believed Every Human Life Has Dignity',
    story: {
      title: 'Mother Teresa',
      years: '1910–1997',
      tagline: 'The Woman Who Believed Every Human Life Has Dignity',
      paragraphs: [
        'Many people looked at the poor and saw a problem.',
        'Mother Teresa looked at the same people and saw a person.',
        'Someone worthy of love.',
        'Someone worthy of care.',
        'Someone whose life mattered.',
        'When she walked through the streets of Calcutta, she did not see crowds.',
        'She saw individuals.',
        'The sick.',
        'The forgotten.',
        'The dying.',
        'The people the world often chose not to notice.',
        'Her greatest gift to humanity was not the hospitals she helped build.',
        'It was the conviction that every human being possesses dignity.',
        'Not because of wealth.',
        'Not because of status.',
        'Not because of achievement.',
        'But simply because they are human.',
        'This belief inspired thousands to serve others with compassion.',
        'It challenged societies to look beyond success, power, and material gain.',
        'And it reminded the world that greatness can be found in the smallest acts of kindness.',
        'Yet Mother Teresa was not a woman untouched by struggle.',
        'She experienced periods of doubt, loneliness, and spiritual darkness throughout her life.',
        'Still, she continued her work.',
        'Not because it was easy.',
        'But because she believed love was a choice.',
        'A commitment renewed day after day.',
        'Her life reminds us that compassion is not a feeling reserved for special moments.',
        'It is a practice.',
        'Her legacy is not a collection of charitable institutions.',
        'Her legacy is a way of seeing other people.',
        'To notice those who are overlooked.',
        'To serve without expecting recognition.',
        'To love without conditions.',
        'And to recognize the worth of every human life.',
        'Long after her work is remembered in history books, this spirit endures.',
        "Every time someone chooses compassion over indifference, offers help to a stranger, or treats another person with dignity, a small part of Mother Teresa's legacy lives on."
      ]
    },
    delay: '1s',
    duration: '3.1s'
  },
  {
    id: 'star-4',
    x: 1045,
    y: 369,
    size: 3,
    label: 'Leonardo da Vinci',
    description: 'The Man Who Believed Curiosity Has No Boundaries',
    story: {
      title: 'Leonardo da Vinci',
      years: '1452–1519',
      tagline: 'The Man Who Believed Curiosity Has No Boundaries',
      paragraphs: [
        'Many people looked at the world and saw separate fields.',
        'Art.',
        'Science.',
        'Engineering.',
        'Nature.',
        'Leonardo looked at the same world and saw no separation at all.',
        'To him, everything was connected.',
        'When he observed a bird in flight, he did not only see movement.',
        'He saw design.',
        'When he studied water flowing through rivers, he did not only see nature.',
        'He saw structure.',
        'And behind every observation, he believed there was a principle waiting to be understood.',
        'His greatest gift to humanity was not a single invention or painting.',
        'It was the conviction that knowledge does not belong to categories.',
        'That beauty and logic are not opposites.',
        'That imagination and observation can coexist in the same mind.',
        'He painted faces that felt alive, not because he tried to imitate reality, but because he tried to understand it.',
        'He sketched machines centuries ahead of their time, not because he wanted to build them immediately, but because he refused to limit what the human mind could explore.',
        'Yet Leonardo was not a man of completion.',
        'Many of his works were unfinished.',
        'Many of his ideas remained sketches.',
        'But in that incompleteness lies part of his legacy.',
        'A reminder that understanding is a lifelong process, not a finished product.',
        'That curiosity itself is the achievement.',
        'His life reminds us that intelligence is not specialization.',
        'It is connection.',
        'The ability to see patterns where others see separation.',
        'To ask questions where others accept boundaries.',
        'And to imagine possibilities that do not yet exist.',
        'His legacy is not a collection of paintings or inventions.',
        'His legacy is a way of thinking.',
        'To observe without limits.',
        'To learn across disciplines.',
        'To connect what others keep apart.',
        'And to never stop questioning how the world works.',
        'Long after his notebooks are studied in museums, this spirit endures.',
        'Every time someone refuses to stay inside a single field and instead follows curiosity wherever it leads, a small part of Leonardo da Vinci’s legacy lives on.'
      ]
    },
    delay: '1.4s',
    duration: '3.8s'
  },
  {
    id: 'star-5',
    x: 650,
    y: 627,
    size: 2,
    label: 'Malala Yousafzai',
    description: 'The Woman Who Believed Education Is a Right That Cannot Be Taken Away',
    story: {
      title: 'Malala Yousafzai',
      years: '1997–',
      tagline: 'The Woman Who Believed Education Is a Right That Cannot Be Taken Away',
      paragraphs: [
        'Many people looked at poverty and saw limitation.',
        'Malala looked at the same world and saw a barrier that could be broken.',
        'Not by force.',
        'Not by privilege.',
        'But by learning.',
        'When she was told that girls should not go to school, she did not accept it as fate.',
        'She saw it as a question.',
        'And behind that question, she believed there must be justice.',
        'Her greatest gift to humanity was not only her courage.',
        'It was the conviction that education is not a privilege for a few.',
        'It is a right for all.',
        'That knowledge is not neutral.',
        'It can liberate.',
        'It can transform.',
        'It can give a child the power to change the course of their own life.',
        'After surviving violence meant to silence her, her voice became even louder.',
        'Not as a voice of anger.',
        'But as a voice of persistence.',
        'A reminder that ideas cannot be stopped by fear alone.',
        'Her life inspired governments, institutions, and generations of young people to reconsider what access to education truly means.',
        'Yet Malala is not merely a symbol of bravery.',
        'She is a reminder of clarity.',
        'That even a single student can challenge the assumptions of an entire system.',
        'Her legacy is not a speech.',
        'Her legacy is a belief.',
        'That every girl, in every country, should be able to learn without fear.',
        'To think freely.',
        'To grow fully.',
        'And to shape her own future.',
        'Long after her story is told in classrooms and books, this spirit endures.',
        'Every time a child walks into a classroom who was once told she did not belong there, a small part of Malala Yousafzai’s legacy lives on.'
      ]
    },
    delay: '0.8s',
    duration: '3.4s'
  },
  {
    id: 'star-6',
    x: 1208,
    y: 650,
    size: 3,
    label: 'Legacy Beacon',
    description: 'Your Legacy - Not yet written.',
    delay: '1.8s',
    duration: '3.7s'
  }
];
